version: '3'

services:
  app:
    image: php:7.2-alpine
    environment:
      TZ: Asia/Tokyo
      APP_CACHE_DIR: /app/data
      FEEDLY_CLIENT_ID: ~
      FEEDLY_CLIENT_SECRET: ~
      POST_TARGET_URL: ~
      POST_FIELD_NAME: ~
    working_dir: /app
    volumes:
      - .:/app
    command: php script/main.php
