version: '3'

services:
  app:
    build: .
    image: feedly-saved-hook
    container_name: feedly-saved-hook
    environment:
      TZ: Asia/Tokyo
      APP_CACHE_DIR: /app/data
      FEEDLY_CLIENT_ID: ~
      FEEDLY_CLIENT_SECRET: ~
      POST_TARGET_URL: ~
      POST_FIELD_NAME: ~
    volumes:
      - data:/app/data

volumes:
  data:
